use crate::ast::{BinaryOp, Expr, MatchPattern, Program, Stmt, UnaryOp};
use crate::type_system::Value;
use std::collections::HashMap;

pub struct Transpiler {
    pub indent_level: usize,
    pub captured_statics: HashMap<String, Value>,
    /// When `true` the state variable is already a `&mut RuntimeState`
    /// (e.g. inside a procedure callback closure) and must be passed
    /// directly to native procedure calls rather than as `&mut state`.
    pub state_is_ref: bool,
}

impl Transpiler {
    pub fn new() -> Self {
        Self::default()
    }
}

impl Default for Transpiler {
    fn default() -> Self {
        Self {
            indent_level: 1,
            captured_statics: HashMap::new(),
            state_is_ref: false,
        }
    }
}

impl Transpiler {
    pub fn with_statics(mut self, statics: HashMap<String, Value>) -> Self {
        self.captured_statics = statics;
        self
    }

    pub fn transpile(mut self, program: &Program) -> String {
        let mut rust_code = String::new();
        rust_code.push_str("// Generated by Corvo Transpiler\n");
        rust_code.push_str("#[allow(unused_imports)]\n");
        rust_code.push_str("use corvo_lang::type_system::Value;\n");
        rust_code.push_str("use corvo_lang::RuntimeState;\n");
        rust_code.push_str("use corvo_lang::CorvoError;\n");
        rust_code.push_str("use std::collections::HashMap;\n\n");

        rust_code.push_str("fn main() {\n");
        rust_code.push_str("    match run() {\n");
        rust_code.push_str("        Ok(_) => {},\n");
        rust_code.push_str("        Err(e) => {\n");
        rust_code.push_str("            eprintln!(\"{}\", e);\n");
        rust_code.push_str("            std::process::exit(e.exit_code());\n");
        rust_code.push_str("        }\n");
        rust_code.push_str("    }\n");
        rust_code.push_str("}\n\n");

        rust_code.push_str("fn run() -> Result<(), CorvoError> {\n");
        rust_code.push_str("    let mut state = RuntimeState::new();\n");
        rust_code.push_str("    state.set_script_argv(std::env::args().skip(1).collect());\n\n");

        // Embed statics
        if !self.captured_statics.is_empty() {
            rust_code.push_str("    // Statics captured during pre-execution\n");
            for (k, v) in &self.captured_statics {
                rust_code.push_str(&format!(
                    "    state.static_set(\"{}\".to_string(), {});\n",
                    k,
                    self.value_to_rust_literal(v)
                ));
            }
            rust_code.push('\n');
        }

        for stmt in &program.statements {
            rust_code.push_str(&self.transpile_stmt(stmt, "state"));
        }

        rust_code.push_str("    Ok(())\n");
        rust_code.push_str("}\n");
        rust_code
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }

    fn transpile_stmt(&mut self, stmt: &Stmt, state_var: &str) -> String {
        let mut code = String::new();
        match stmt {
            Stmt::VarSet { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                // Compute RHS into a temp first so that the borrow of `state`
                // inside `val_expr` ends before `var_set` mutably borrows it.
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let __corvo_rhs = {};\n",
                    self.indent(),
                    val_expr
                ));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), __corvo_rhs);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::StaticSet { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                // Same temp-variable pattern as VarSet to avoid double borrow.
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let __corvo_rhs = {};\n",
                    self.indent(),
                    val_expr
                ));
                code.push_str(&format!(
                    "{}    {}.static_set(\"{}\".to_string(), __corvo_rhs);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarIndexSet { name, index, value } => {
                let idx_expr = self.transpile_expr(index, state_var);
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let current = {}.var_get(\"{}\")?;\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}    let index = {};\n", self.indent(), idx_expr));
                code.push_str(&format!(
                    "{}    let new_val = {};\n",
                    self.indent(),
                    val_expr
                ));
                code.push_str(&format!(
                    "{}    let updated = match (&current, &index) {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        (Value::Map(map), Value::String(key)) => {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            let mut new_map = map.clone();\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            new_map.insert(key.clone(), new_val);\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            Value::Map(new_map)\n",
                    self.indent()
                ));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        (Value::List(list), Value::Number(idx)) => {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            let mut new_list = list.clone();\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            let i = *idx as usize;\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            if i >= new_list.len() {{ return Err(CorvoError::runtime(\"Index out of bounds\")); }}\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            new_list[i] = new_val;\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            Value::List(new_list)\n",
                    self.indent()
                ));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        _ => return Err(CorvoError::r#type(\"Invalid index set\")),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}    }};\n", self.indent()));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), updated);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarAddAssign { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let current = {}.var_get(\"{}\")?;\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}    let rhs = {};\n", self.indent(), val_expr));
                code.push_str(&format!(
                    "{}    let updated = match (current, rhs) {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        (Value::Number(a), Value::Number(b)) => Value::Number(a + b),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}        (Value::String(a), Value::String(b)) => Value::String(format!(\"{{}}{{}}\", a, b)),\n", self.indent()));
                code.push_str(&format!(
                    "{}        _ => return Err(CorvoError::r#type(\"+= fails\")),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}    }};\n", self.indent()));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), updated);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarSubAssign { name, value } => {
                let val_expr = self.transpile_expr(value, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let current = {}.var_get(\"{}\")?;\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}    let rhs = {};\n", self.indent(), val_expr));
                code.push_str(&format!(
                    "{}    let updated = match (current, rhs) {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        (Value::Number(a), Value::Number(b)) => Value::Number(a - b),\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}        _ => return Err(CorvoError::r#type(\"-= fails\")),\n",
                    self.indent()
                ));
                code.push_str(&format!("{}    }};\n", self.indent()));
                code.push_str(&format!(
                    "{}    {}.var_set(\"{}\".to_string(), updated);\n",
                    self.indent(),
                    state_var,
                    name
                ));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::VarOrAssign { name, candidates } => {
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    if !{}.var_get(\"{}\").unwrap_or(Value::Null).is_truthy() {{\n",
                    self.indent(),
                    state_var,
                    name
                ));
                // Use a labeled block so that we can `break '__corvo_or` to stop
                // trying further candidates once one is truthy.  A plain `break`
                // is not valid outside a loop, and a loop-based approach cannot
                // be broken from inside closures (e.g. inside TryBlock fallbacks).
                // `break 'label` for a label defined inside the same closure IS
                // always valid in Rust.
                code.push_str(&format!("{}        '__corvo_or: {{\n", self.indent()));
                self.indent_level += 3;
                for cand in candidates {
                    let cand_expr = self.transpile_expr(cand, state_var);
                    code.push_str(&format!("{}let __val = {};\n", self.indent(), cand_expr));
                    code.push_str(&format!("{}if __val.is_truthy() {{\n", self.indent()));
                    code.push_str(&format!(
                        "{}    {}.var_set(\"{}\".to_string(), __val);\n",
                        self.indent(),
                        state_var,
                        name
                    ));
                    code.push_str(&format!("{}    break '__corvo_or;\n", self.indent()));
                    code.push_str(&format!("{}}}\n", self.indent()));
                }
                self.indent_level -= 3;
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!("{}    }}\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::ExprStmt { expr } => {
                let expr_code = self.transpile_expr(expr, state_var);
                code.push_str(&format!("{}{};\n", self.indent(), expr_code));
            }
            Stmt::Loop { body } => {
                code.push_str(&format!("{}loop {{\n", self.indent()));
                self.indent_level += 1;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                self.indent_level -= 1;
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Browse {
                iterable,
                key,
                value,
                body,
            } => {
                let iter_expr = self.transpile_expr(iterable, state_var);
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let iter_val = {};\n",
                    self.indent(),
                    iter_expr
                ));
                code.push_str(&format!("{}    match iter_val {{\n", self.indent()));
                code.push_str(&format!(
                    "{}        Value::List(list) => {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            for (i, item) in list.iter().enumerate() {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}                {}.var_set(\"{}\".to_string(), Value::Number(i as f64));\n",
                    self.indent(),
                    state_var,
                    key
                ));
                code.push_str(&format!(
                    "{}                {}.var_set(\"{}\".to_string(), item.clone());\n",
                    self.indent(),
                    state_var,
                    value
                ));
                self.indent_level += 4;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                self.indent_level -= 4;
                code.push_str(&format!("{}            }}\n", self.indent()));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!("{}        Value::Map(map) => {{\n", self.indent()));
                code.push_str(&format!(
                    "{}            let mut entries: Vec<_> = map.into_iter().collect();\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            entries.sort_by(|a, b| a.0.cmp(&b.0));\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            for (k, v) in entries {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}                {}.var_set(\"{}\".to_string(), Value::String(k));\n",
                    self.indent(),
                    state_var,
                    key
                ));
                code.push_str(&format!(
                    "{}                {}.var_set(\"{}\".to_string(), v);\n",
                    self.indent(),
                    state_var,
                    value
                ));
                self.indent_level += 4;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                self.indent_level -= 4;
                code.push_str(&format!("{}            }}\n", self.indent()));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!("{}        _ => return Err(CorvoError::r#type(\"browse only works on lists and maps\")),\n", self.indent()));
                code.push_str(&format!("{}    }}\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Terminate => {
                code.push_str(&format!("{}return Ok(());\n", self.indent()));
            }
            Stmt::TryBlock { body, fallbacks } => {
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let mut result = (|| -> Result<(), CorvoError> {{\n",
                    self.indent()
                ));
                self.indent_level += 2;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                code.push_str(&format!("{}Ok(())\n", self.indent()));
                self.indent_level -= 2;
                code.push_str(&format!("{}    }})();\n", self.indent()));
                code.push_str(&format!("{}    if result.is_err() {{\n", self.indent()));
                self.indent_level += 1;
                for fb in fallbacks {
                    code.push_str(&format!(
                        "{}result = (|| -> Result<(), CorvoError> {{\n",
                        self.indent()
                    ));
                    self.indent_level += 1;
                    for s in &fb.body {
                        code.push_str(&self.transpile_stmt(s, state_var));
                    }
                    code.push_str(&format!("{}Ok(())\n", self.indent()));
                    self.indent_level -= 1;
                    code.push_str(&format!("{}    }})();\n", self.indent()));
                    code.push_str(&format!(
                        "{}if result.is_ok() {{ /* break fallback loop */ }}\n",
                        self.indent()
                    ));
                }
                self.indent_level -= 1;
                code.push_str(&format!("{}    }}\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::Assert { kind, args } => {
                let arg_list: Vec<String> = args
                    .iter()
                    .map(|a| self.transpile_expr(a, state_var))
                    .collect();
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let values = vec![{}];\n",
                    self.indent(),
                    arg_list.join(", ")
                ));
                code.push_str(&format!(
                    "{}    match corvo_lang::ast::AssertKind::{:?} {{\n",
                    self.indent(),
                    kind
                ));
                code.push_str(&format!(
                    "{}        corvo_lang::ast::AssertKind::Eq => {{\n",
                    self.indent()
                ));
                code.push_str(&format!("{}            if values.len() != 2 || values[0] != values[1] {{ return Err(CorvoError::assertion(format!(\"{{}} != {{}}\", values[0], values[1]))); }}\n", self.indent()));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        corvo_lang::ast::AssertKind::Neq => {{\n",
                    self.indent()
                ));
                code.push_str(&format!("{}            if values.len() != 2 || values[0] == values[1] {{ return Err(CorvoError::assertion(format!(\"{{}} == {{}}\", values[0], values[1]))); }}\n", self.indent()));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        corvo_lang::ast::AssertKind::Gt => {{\n",
                    self.indent()
                ));
                code.push_str(&format!("{}            if values.len() != 2 || values[0].as_number().unwrap_or(0.0) <= values[1].as_number().unwrap_or(0.0) {{ return Err(CorvoError::assertion(format!(\"{{}} <= {{}}\", values[0], values[1]))); }}\n", self.indent()));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        corvo_lang::ast::AssertKind::Lt => {{\n",
                    self.indent()
                ));
                code.push_str(&format!("{}            if values.len() != 2 || values[0].as_number().unwrap_or(0.0) >= values[1].as_number().unwrap_or(0.0) {{ return Err(CorvoError::assertion(format!(\"{{}} >= {{}}\", values[0], values[1]))); }}\n", self.indent()));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!(
                    "{}        corvo_lang::ast::AssertKind::Match => {{\n",
                    self.indent()
                ));
                code.push_str(&format!(
                    "{}            if values.len() != 2 || !{{\n",
                    self.indent()
                ));
                code.push_str(&format!("{}                let pattern = values[0].as_string().ok_or_else(|| CorvoError::r#type(\"assert_match requires strings\"))?;\n", self.indent()));
                code.push_str(&format!("{}                let target = values[1].as_string().ok_or_else(|| CorvoError::r#type(\"assert_match requires strings\"))?;\n", self.indent()));
                code.push_str(&format!("{}                let re = regex::Regex::new(pattern).map_err(|e| CorvoError::runtime(e.to_string()))?;\n", self.indent()));
                code.push_str(&format!(
                    "{}                re.is_match(target)\n",
                    self.indent()
                ));
                code.push_str(&format!("{}            }} {{ return Err(CorvoError::assertion(format!(\"{{}} does not match {{}}\", values[0], values[1]))); }}\n", self.indent()));
                code.push_str(&format!("{}        }}\n", self.indent()));
                code.push_str(&format!("{}    }}\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::DontPanic { body } => {
                code.push_str(&format!("{}{{\n", self.indent()));
                code.push_str(&format!(
                    "{}    let _ = (|| -> Result<(), CorvoError> {{\n",
                    self.indent()
                ));
                self.indent_level += 2;
                for s in body {
                    code.push_str(&self.transpile_stmt(s, state_var));
                }
                code.push_str(&format!("{}Ok(())\n", self.indent()));
                self.indent_level -= 2;
                code.push_str(&format!("{}    }})();\n", self.indent()));
                code.push_str(&format!("{}}}\n", self.indent()));
            }
            Stmt::PrepBlock { .. } => {
                // Prep blocks are evaluated at compile time, so we skip them here.
            }
            Stmt::AsyncBrowse {
                list,
                proc_name,
                item_param,
                shared_vars,
            } => {
                let list_expr = self.transpile_expr(list, state_var);
                let shared_list = shared_vars
                    .iter()
                    .map(|v| format!("{:?}.to_string()", v))
                    .collect::<Vec<_>>()
                    .join(", ");
                code.push_str(&format!(
                    "{}corvo_lang::compiler::Evaluator::new().exec_async_browse_native(\n\
                     {}    match {} {{ Value::List(l) => l, _ => return Err(CorvoError::r#type(\"async_browse requires a list\")) }},\n\
                     {}    match {}.var_get({:?})? {{ Value::NativeProcedure {{ params: ref p, .. }} => p.clone(), _ => return Err(CorvoError::r#type(\"async_browse expects a procedure\")) }},\n\
                     {}    match {}.var_get({:?})? {{ Value::NativeProcedure {{ callback: ref p, .. }} => p.clone(), _ => return Err(CorvoError::r#type(\"async_browse expects a procedure\")) }},\n\
                     {}    {:?},\n\
                     {}    &[{}],\n\
                     {}    &mut {}\n\
                     {})?;\n",
                    self.indent(),
                    self.indent(),
                    list_expr,
                    self.indent(),
                    state_var,
                    proc_name,
                    self.indent(),
                    state_var,
                    proc_name,
                    self.indent(),
                    item_param,
                    self.indent(),
                    shared_list,
                    self.indent(),
                    state_var,
                    self.indent()
                ));
            }
        }
        code
    }

    fn transpile_expr(&mut self, expr: &Expr, state_var: &str) -> String {
        match expr {
            Expr::Literal { value } => self.value_to_rust_literal(value),
            Expr::VarGet { name } => format!("{}.var_get(\"{}\")?", state_var, name),
            Expr::StaticGet { name } => format!("{}.static_get(\"{}\")?", state_var, name),
            Expr::Binary { op, left, right } => {
                let l = self.transpile_expr(left, state_var);
                let r = self.transpile_expr(right, state_var);
                let op_str = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Sub => "-",
                    BinaryOp::Mul => "*",
                    BinaryOp::Div => "/",
                };
                format!("match ({}, {}) {{ (Value::Number(a), Value::Number(b)) => Value::Number(a {} b), _ => return Err(CorvoError::r#type(\"Arithmetic error\")) }}", l, r, op_str)
            }
            Expr::Unary { op, operand } => {
                let v = self.transpile_expr(operand, state_var);
                match op {
                    UnaryOp::Neg => format!("match {} {{ Value::Number(n) => Value::Number(-n), _ => return Err(CorvoError::r#type(\"Negation error\")) }}", v),
                }
            }
            Expr::StringInterpolation { parts } => {
                let mut p_codes = Vec::new();
                for p in parts {
                    p_codes.push(format!("{}.to_string()", self.transpile_expr(p, state_var)));
                }
                format!(
                    "Value::String(format!(\"{}\", {}))",
                    "{}".repeat(parts.len()),
                    p_codes.join(", ")
                )
            }
            Expr::FunctionCall {
                name,
                args,
                named_args,
            } => {
                let args_list: Vec<String> = args
                    .iter()
                    .map(|a| self.transpile_expr(a, state_var))
                    .collect();
                let mut named_map_items = Vec::new();
                for (k, v) in named_args {
                    named_map_items.push(format!(
                        "(\"{}\".to_string(), {})",
                        k,
                        self.transpile_expr(v, state_var)
                    ));
                }
                let named_map_code = if named_map_items.is_empty() {
                    "HashMap::new()".to_string()
                } else {
                    format!("HashMap::from([{}])", named_map_items.join(", "))
                };
                if name == "__list__" {
                    format!("Value::List(vec![{}])", args_list.join(", "))
                } else if name == "__map__" {
                    format!("Value::Map({})", named_map_code)
                } else {
                    format!(
                        "corvo_lang::standard_lib::call(\"{}\", &[{}], &{}, &{})?",
                        name,
                        args_list.join(", "),
                        named_map_code,
                        state_var
                    )
                }
            }
            Expr::MethodCall {
                target,
                method,
                args,
                named_args,
            } => {
                let target_code = self.transpile_expr(target, state_var);
                let args_list: Vec<String> = args
                    .iter()
                    .map(|a| self.transpile_expr(a, state_var))
                    .collect();
                let mut named_map_items = Vec::new();
                for (k, v) in named_args {
                    named_map_items.push(format!(
                        "(\"{}\".to_string(), {})",
                        k,
                        self.transpile_expr(v, state_var)
                    ));
                }
                let named_map_code = if named_map_items.is_empty() {
                    "HashMap::new()".to_string()
                } else {
                    format!("HashMap::from([{}])", named_map_items.join(", "))
                };

                let mut outer_names_code = Vec::new();
                for a in args {
                    if let Expr::VarGet { name } = a {
                        outer_names_code.push(format!("Some({:?}.to_string())", name));
                    } else {
                        outer_names_code.push("None".to_string());
                    }
                }
                let outer_names_list = outer_names_code.join(", ");

                // When `state_var` is already a `&mut RuntimeState` reference
                // (inside a procedure callback closure) pass it directly to the
                // native callback.  In the outer `run()` function `state` is a
                // plain `RuntimeState` value and must be taken by `&mut`.
                let state_arg = if self.state_is_ref {
                    state_var.to_string()
                } else {
                    format!("&mut {}", state_var)
                };

                format!(
                    "{{\n    \
                    let t = {};\n    \
                    if {:?} == \"call\" && matches!(t, Value::NativeProcedure {{ .. }}) {{\n        \
                        if let Value::NativeProcedure {{ params: p_names, callback: p }} = t {{\n            \
                            let arg_vals = vec![{}];\n            \
                            let outer_names: Vec<Option<String>> = vec![{}];\n            \
                            let saved: Vec<Option<Value>> = p_names.iter().map(|p| {}.var_remove(p)).collect();\n            \
                            let res = (p)(&arg_vals, {})?;\n            \
                            for (i, param) in p_names.iter().enumerate() {{\n                \
                                if let Some(Some(outer_name)) = outer_names.get(i) {{\n                    \
                                    let updated = {}.var_get(param.as_str()).unwrap_or(Value::Null);\n                    \
                                    {}.var_set(outer_name.clone(), updated);\n                \
                                }}\n                \
                                {}.var_remove(param.as_str());\n                \
                                if let Some(prev) = saved[i].clone() {{\n                    \
                                    {}.var_set(param.to_string(), prev);\n                \
                                }}\n            }}\n            \
                            res\n        \
                        }} else {{ unreachable!() }}\n    \
                    }} else {{\n        \
                        let mut a = vec![t.clone()];\n        \
                        a.extend(vec![{}]);\n        \
                        let ns = match &t {{\n            \
                            Value::String(_) => \"string\",\n            \
                            Value::Number(_) => \"number\",\n            \
                            Value::List(_) => \"list\",\n            \
                            Value::Map(_) => \"map\",\n            \
                            Value::Regex(_, _) => \"re\",\n            \
                            Value::Procedure(_) | Value::NativeProcedure {{ .. }} => \"procedure\",\n            \
                            _ => return Err(CorvoError::r#type(\"method call error\"))\n        }};\n        \
                        corvo_lang::standard_lib::call(&format!(\"{{}}.{{}}\", ns, {:?}), &a, &{}, &{})?\n\
                    }}\n\
                    }}",
                    target_code,
                    method,
                    args_list.join(", "),
                    outer_names_list,
                    state_var,
                    state_arg,
                    state_var,
                    state_var,
                    state_var,
                    state_var,
                    args_list.join(", "),
                    method,
                    named_map_code,
                    state_var
                )
            }
            Expr::Match { value, arms } => {
                let val_code = self.transpile_expr(value, state_var);
                let mut arms_code = Vec::new();
                let mut has_wildcard = false;
                for arm in arms {
                    let pat = match &arm.pattern {
                        MatchPattern::Literal(v) => {
                            format!("__corvo_match_val if __corvo_match_val == {}", self.value_to_rust_literal(v))
                        }
                        MatchPattern::Wildcard => {
                            has_wildcard = true;
                            "_".to_string()
                        }
                        MatchPattern::Regex(p, f) => format!(
                            "__corvo_match_val if __corvo_match_val == Value::Regex({:?}.to_string(), {:?}.to_string())",
                            p, f
                        ),
                    };
                    arms_code.push(format!(
                        "{} => {},",
                        pat,
                        self.transpile_expr(&arm.body, state_var)
                    ));
                }
                if has_wildcard {
                    format!("match {} {{ {} }}", val_code, arms_code.join(" "))
                } else {
                    format!(
                        "match {} {{ {} _ => Value::Null }}",
                        val_code,
                        arms_code.join(" ")
                    )
                }
            }
            Expr::IndexAccess { target, index } => {
                let t = self.transpile_expr(target, state_var);
                let i = self.transpile_expr(index, state_var);
                format!("match ({}, {}) {{\n    (Value::List(l), Value::Number(idx)) => l.get(idx as usize).cloned().ok_or_else(|| CorvoError::runtime(\"Index out of bounds\"))?,\n    (Value::Map(m), Value::String(key)) => m.get(&key).cloned().ok_or_else(|| CorvoError::runtime(format!(\"Key not found: {{}}\", key)))?,\n    _ => return Err(CorvoError::r#type(\"index access error\"))\n}}", t, i)
            }
            Expr::SliceAccess { target, start, end } => {
                let t = self.transpile_expr(target, state_var);
                let s = match start {
                    Some(e) => format!(
                        "Some({}.as_number().unwrap_or(0.0) as usize)",
                        self.transpile_expr(e, state_var)
                    ),
                    None => "None".to_string(),
                };
                let e = match end {
                    Some(e) => format!(
                        "Some({}.as_number().unwrap_or(0.0) as usize)",
                        self.transpile_expr(e, state_var)
                    ),
                    None => "None".to_string(),
                };
                format!("{{\n    let t = {};\n    match t {{\n        Value::List(l) => {{\n            let start = {}.unwrap_or(0);\n            let end = {}.unwrap_or(l.len());\n            Value::List(l[start.min(l.len())..end.min(l.len())].to_vec())\n        }}\n        Value::String(s) => {{\n            let start = {}.unwrap_or(0);\n            let end = {}.unwrap_or(s.len());\n            Value::String(s[start.min(s.len())..end.min(s.len())].to_string())\n        }}\n        _ => return Err(CorvoError::r#type(\"slice access error\"))\n    }}\n}}", t, s, e, s, e)
            }
            Expr::ProcedureLiteral { params, body } => {
                let mut proc_code = String::new();
                proc_code.push_str("Value::NativeProcedure {\n");
                proc_code.push_str(&format!(
                    "    params: vec![{}],\n",
                    params
                        .iter()
                        .map(|p| format!("{:?}.to_string()", p))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
                proc_code.push_str(
                    "    callback: std::sync::Arc::new(|args: &[Value], state: &mut RuntimeState| {\n",
                );

                // Bind parameters
                proc_code.push_str(&format!("    if args.len() < {} {{ return Err(CorvoError::runtime(format!(\"Procedure expects at least {} arguments, got {{}}\", args.len()))); }}\n", params.len(), params.len()));
                for (i, p) in params.iter().enumerate() {
                    proc_code.push_str(&format!(
                        "    state.var_set(\"{}\".to_string(), args[{}].clone());\n",
                        p, i
                    ));
                }

                // Transpile body
                // `state_is_ref: true` because the closure parameter is
                // `state: &mut RuntimeState` (already a reference).
                let mut sub_transpiler = Transpiler {
                    indent_level: 1,
                    captured_statics: self.captured_statics.clone(),
                    state_is_ref: true,
                };
                for stmt in body {
                    proc_code.push_str(&sub_transpiler.transpile_stmt(stmt, "state"));
                }

                proc_code.push_str("    Ok(Value::Null)\n");
                proc_code.push_str("}),\n}");
                proc_code
            }
            _ => "Value::Null".to_string(),
        }
    }

    fn value_to_rust_literal(&self, value: &Value) -> String {
        match value {
            Value::Null => "Value::Null".to_string(),
            Value::Boolean(b) => format!("Value::Boolean({})", b),
            Value::Number(n) => format!("Value::Number({:?})", n),
            Value::String(s) => format!("Value::String({:?}.to_string())", s),
            Value::List(items) => {
                let inner: Vec<String> = items
                    .iter()
                    .map(|v| self.value_to_rust_literal(v))
                    .collect();
                format!("Value::List(vec![{}])", inner.join(", "))
            }
            Value::Map(m) => {
                let mut entries = Vec::new();
                for (k, v) in m {
                    entries.push(format!(
                        "(\"{}\".to_string(), {})",
                        k,
                        self.value_to_rust_literal(v)
                    ));
                }
                format!("Value::Map(HashMap::from([{}]))", entries.join(", "))
            }
            Value::Regex(p, f) => format!("Value::Regex({:?}.to_string(), {:?}.to_string())", p, f),
            Value::NativeProcedure { params, .. } => {
                let p_expr = params
                    .iter()
                    .map(|p| format!("{:?}.to_string()", p))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "Value::NativeProcedure {{ params: vec![{}], callback: std::sync::Arc::new(|_, _| Ok(Value::Null)) }}",
                    p_expr
                )
            }
            _ => "Value::Null".to_string(),
        }
    }
}
